import csv
import argparse
from pathlib import Path
from wand.image import Image

THUMB_DESIGNATOR = '_thumb'
THUMB_SIZE = 'x390'
MED_DESIGNATOR = '_med'
MED_SIZE = 'x900'

ap = argparse.ArgumentParser()
ap.add_argument("-i", "--input", required=True, \
    help="Path to the input file generated by tacc_check.py.")

args = vars(ap.parse_args())
input_file = args['input']

def create_derivative(web_image_path=None, derivative_designator=None):
    # Will generate new derivative if needed
    if web_image_path.exists():
        # Create derivative name
        derivative_file_name = full_image_path.stem + derivative_designator + full_image_path.suffix
        # Check if derivative image currently exists
        derivative_file_path = full_image_path.parent.joinpath(derivative_file_name)
        #print('thumb_file_path:', thumb_file_path)
        if derivative_file_path.exists():
            print('Derivative exists:', derivative_file_path)
        else:
            # Generate derivative
            generate_derivative(source_path=web_image_path, derivative_path=derivative_file_path, derivative_designator=derivative_designator)
    else:
        print('Full image missing:', web_image_path)

def generate_derivative(source_path=None, derivative_path=None, derivative_designator=None):
    if derivative_designator == THUMB_DESIGNATOR:
        dimension = THUMB_SIZE
    if derivative_designator == MED_DESIGNATOR:
        dimension = MED_SIZE
    try:
        with Image(filename=source_path) as original:
            with original.clone() as derivative:
                # resize height, preserve aspect ratio
                derivative.transform(resize=dimension)
                derivative.save(filename=derivative_path)
    except Exception as e:
        print('Unable to create derivative:', e)


with open(input_file) as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        #print(row['catalog_number'])
        if row['web_jpg_path']:
            #print(row['web_jpg_path'])
            full_image_path = Path(row['web_jpg_path'])
            # TODO: log new, complete records
            if not row['web_jpg_thumb_path']:
                print('missing thumb record:', row['web_jpg_path'])
                # Create thumb derivative if needed
                create_derivative(web_image_path=full_image_path, derivative_designator=THUMB_DESIGNATOR)
            if not row['web_jpg_med_path']:
                print('missing med record:', row['web_jpg_path'])
                create_derivative(web_image_path=full_image_path, derivative_designator=MED_DESIGNATOR)
